FROM golang:1.15.5-buster as build

ENV GOPATH /go
ENV GO111MODULE on

WORKDIR ${GOPATH}/src

COPY . ./

RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o main

FROM golang:1.15.5-buster

COPY --from=build /go/src/main ./main
RUN chmod +x main

ENTRYPOINT ["./main"]